# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-Cover
version:      0.53
version_from: 
installdirs:  site
requires:
    Digest::MD5:                   0
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
